"updates":
- "directory": "/"
  "package-ecosystem": "github-actions"
  "schedule":
    "interval": "monthly"
- "directory": "/"
  "package-ecosystem": "gitsubmodule"
  "schedule":
    "interval": "monthly"
- "directory": "/"
  "package-ecosystem": "gomod"
  "schedule":
    "interval": "monthly"
"version": 2
