name: Dependabot auto-merge
on:
  workflow_run:
    branches:
      - dependabot/go_modules/**
      - dependabot/submodules/**
    types:
      - completed
    workflows:
      - 'Continuous integration'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Enable auto-merge for Dependabot PRs
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"
